### ISSUE TITLE
Refactor velocity-related behavior in continuous motors

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/concert#340]
### Problem

Currently we have a parameter `velocity` which works as expected, it sets the motion velocity (from now on velo_constant) and starts moving. The problem is that velo_constant is then probably used also for the next motion.
I have seen this behavior already quite a lot so maybe we should distinguish the real `immediate_velocity` and velo_constant.
Another fact in favour of having velo_constant is stashing. If one stashes a motor device now and restores it is useless, because the `position` is restored and then it starts moving anyway because `velocity` is restored as well.
### Example

``` python
# move with whatever velocity is set on the controller
motor.position = 10 * q.deg
motor.velocity = 40 * q.deg / q.s
motor.stop().join()
# Here we most probably move with 40 deg/s set by the previous motor.velocity command
motor.position = 0 * q.deg
```
### Solution

We could have `velocity` as a read/write attribute which is the "velocity used by the next motion command", i.e. `set_position`, `move`, `home`, etc. Then we can have a read-only parameter `immediate_velocity` which would give the current motor velocity (also easy to fake in software in case it is needed). We already have a `stop` method, so we can add `start` for starting continuous motion (asynchronous, but the real implementations would wait until the motion is steady like it is now).
So this:

``` python
motor.velocity = 10 * q.deg / q.s
```

would be replaced by this:

``` python
# longer
motor.velocity = 10 * q.deg / q.s
motor.start().join()
# do a tomogram or whatever
motor.stop().join()
# change the velocity
motor.velocity = 10 * q.deg / q.s
# but here we know what we are doing
motor.position = 0 * q.deg
```

**Comment by MarcusZuber** [comment]
Now we use this a little bit different.
The velocity property reads the "measured" velocity and setting it issues a velocity controlled motion. The motion-velocity is the target velocity for a position controlled motion (= setting the position porperty).
Unfortuanetly some hardware mix both values up which can result in a change from the motion-velocty by setting velocity and vice versa. This should be handled in the specific device implementation (e.g. with stash/restore if possible)

In addition, using the 'target_value' properly for the velocity and position property will not result in an unwanted motion due to a noisy measured velocity (since the target value sould be 0 if no movelemnt is issued).

I think we can close this issue. @tfarago What do you think?
